language: ruby
rvm:
- 2.0.0
branches:
  only:
  - master
script: rake travis
env:
  global:
    secure: "QZAqhZVmt9+BxNCA3qzp1WZkw0Jra9OFtbXnrVlnjm1USwLlhL0SmbLq1AKAfe93Nd6coZ6Lcxby3aw2ANE0uNXy9ZqVHQbbzMN7wpBsxIhnrJKPAyRMrhWXjfwjsrdNQS/TkW4IUsj4h3oDNyl0t416swd8rZ+hdO7Wo737OYs="
